# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: My Test of GitHubActions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  Amos_Pa_lla:

    runs-on: ubuntu-latest

    steps:
      #Step 1 : Checkout the code from repository: (only last commit...the one that trigger the action)
    - name: Checkout code 
      uses: actions/checkout@v4

      #Step "2" : Install python (last current version in my laptop Aug 2025)
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.3"
    
      #Step "3" : Install Dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      # python -m pip install --upgrade pip (due to an error)
        
      
    #Step "3" : Install Dependencies
    - name: Test with pytest
      run: |
        pytest
